---
plugin: gcp_compute
projects:
  - infra-262323
zones:
  - europe-west1-b
groups:
  app: "'-app' in name"
  db: "'-db' in name"
filters: []

hostnames:
  - name
compose:
   ansible_host: networkInterfaces[0].accessConfigs[0].natIP

auth_kind: serviceaccount
service_account_file: infra-262323-966e950708f6.json
